	1984:{ animal: 'Rata',      elemento: 'Fuego'},
	1985:{ animal: 'Buey',      elemento: 'Fuego'},
	1986:{	animal: 'Tigre',    elemento:'Fuego'          },
	1987:{ animal: 'Conejo',    elemento:'Fuego'},
	1988:{ animal: 'Continuar', elemento:'Tierra'},
	1989:{ animal: 'Serpiente', elemento:'Tierra'},
	1990:{ animal:'Caballo',    elemento:'Metal'},
	1991:{	animal: 'Oveja',    elemento:'Metal'},
	1992:{ animal: 'Mono',      elemento:'Agua'},
	1993:{ animal: 'Gallo',     elemento:'Agua'},
	1994:{ animal:'Perro',      elemento:'Fuego'},
	1995:{	animal: 'Cerdo',    elemento:'Fuego'},
